### ISSUE TITLE
Скачивание плейлистов?

### ISSUE THREAD

**Issue by ZeoNish** [vknext/vk-music-saver#4]
Нет такого функционала вроде

**Comment by ZeoNish** [comment]
Как предложение по интеграции 
![image](https://github.com/user-attachments/assets/dcf3fd6f-3107-4626-9ead-bd1dd937bfd9)

**Comment by awers24** [comment]
> Нет такого функционала вроде

есть, кнопка расположена в контекстом меню плейлиста:
![image](https://github.com/user-attachments/assets/6d76ed24-23b9-4452-9e27-e4e25b761e35)
Возможно вам включили новый дизайн плейлистов, тогда да, может не быть.

**Comment by awers24** [comment]
> Как предложение по интеграции для .audio_page__shuffle_all добавляем display: flex; ![image](https://private-user-images.githubusercontent.com/8596319/369308759-dcf3fd6f-3107-4626-9ead-bd1dd937bfd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjAzNDYsIm5iZiI6MTcyNjgyMDA0NiwicGF0aCI6Ii84NTk2MzE5LzM2OTMwODc1OS1kY2YzZmQ2Zi0zMTA3LTQ2MjYtOWVhZC1iZDFkZDkzN2JmZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMDgxNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAzMmYwMjVkYjJiYmY0NWM0YzFkMzBhM2E2YTU1NzBjZDBmNjljOGJjMDAyYTJjOWQwZWY0M2Q2YjNiN2UxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J9FV1yt5ewq_JsF6_JN91iNXOv1O7ttpUMzguN6cP7A)
> 
> И новая кнопка "Скачать все"

это реализовано в [основном расширении](https://vknext.net), в VK Music Saver ещё не перенесли

**Comment by ZeoNish** [comment]
Етить... 

> > Нет такого функционала вроде
> 
> есть, кнопка расположена в контекстом меню плейлиста: ![image](https://private-user-images.githubusercontent.com/83694881/369323265-6d76ed24-23b9-4452-9e27-e4e25b761e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjA1NjgsIm5iZiI6MTcyNjgyMDI2OCwicGF0aCI6Ii84MzY5NDg4MS8zNjkzMjMyNjUtNmQ3NmVkMjQtMjNiOS00NDUyLTllMjctZTRlMjViNzYxZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA4MTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZWRkYzJiYTQ2ZTExY2NhNWI1YzE5MzhmMDlhMDA3NjBlMTgxNTU2N2Y1NTVmMjk0NGExMWUxMzQyNWI2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rN0Fj99uJmFaz4lBqusBdLIZHc4YtJ2Q8aBDHFNq4as) Возможно вам включили новый дизайн плейлистов, тогда да, может не быть.


Не видел...
